# Numpy Exercise

#### 1. Import the numpy package under the name as np  

In [1]:
import numpy as np

#### 2. Print the numpy version and the configuration 

In [53]:
print("Numpy version is: \n", np.__version__)
print("Numpy configuration is:")
np.__config__.show()

Numpy version is: 
 1.18.5
Numpy configuration is:
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/kanna/anaconda\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'C:/Users/kanna/anaconda\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/kanna/anaconda\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compiler

#### 3. Create a null vector of size 10

In [4]:
null_vector = np.zeros(10)
print(null_vector)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4.  How to find the memory size of any array

In [8]:
n = np.zeros((4,3))
print("Number of elements in the array: ", n.size)
print("Memory size of numpy array in bytes: ", n.size * n.itemsize)

Number of elements in the array:  12
Memory size of numpy array in bytes:  96


#### 5.  How to get the documentation of the numpy add function from the command line? 

In [9]:
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added. If ``x1.shape != x2.shape``, they must be broadcastable to a common shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out=None``,

#### 6.  Create a null vector of size 10 but the fifth value which is 1

In [11]:
null_vector = np.zeros(10)
null_vector[4] = 1
print(null_vector)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7.  Create a vector with values ranging from 10 to 49

In [13]:
n = np.arange(10,50)
print(n)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8.  Reverse a vector (first element becomes last)

In [14]:
n = n[::-1]
print(n)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


#### 9.  Create a 3x3 matrix with values ranging from 0 to 8

In [15]:
n = np.arange(0,9)
z = n.reshape(3,3)
print(z)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\]

In [18]:
n = np.array([1,2,0,0,4,0])
z = np.array(n>0)
print(z)
x = np.nonzero(n)
print(x)

[ True  True False False  True False]
(array([0, 1, 4], dtype=int64),)


#### 11. Create a 3x3 identity matrix

In [19]:
n = np.eye(3)
print(n)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values

In [20]:
n = np.random.random((3,3,3))
print(n)

[[[0.99760839 0.67055605 0.28171802]
  [0.10280107 0.53302981 0.98714179]
  [0.13752404 0.42259074 0.21663591]]

 [[0.51914659 0.03045789 0.69724848]
  [0.62066964 0.63226831 0.82706347]
  [0.71050372 0.53602582 0.69229049]]

 [[0.20133679 0.42933632 0.93556625]
  [0.6096135  0.81668702 0.41690319]
  [0.92148959 0.51088677 0.70855408]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values

In [24]:
n = np.random.random((10,10))
print("Random Array : \n",n)
print("Maximum value: ", n.max())
print("Minimum value: ", n.min())

Random Array : 
 [[0.88075088 0.38400249 0.62397024 0.34272937 0.48406843 0.72129757
  0.91230684 0.59252618 0.01872995 0.46679654]
 [0.33726409 0.64038657 0.63474184 0.18530644 0.45658425 0.94197318
  0.50516796 0.03762098 0.31888722 0.88729212]
 [0.83391982 0.48444272 0.73395968 0.4665439  0.81061159 0.13293986
  0.12548709 0.38831563 0.8024677  0.71214932]
 [0.30313042 0.29162698 0.45868391 0.46498365 0.38770615 0.82769642
  0.06955111 0.66801716 0.12517709 0.19129244]
 [0.27541016 0.95046415 0.28617234 0.05599836 0.87341554 0.22049131
  0.13689997 0.96050894 0.80426937 0.10063465]
 [0.93585236 0.0267966  0.71512576 0.06794341 0.07713335 0.880106
  0.23856177 0.66306849 0.53649853 0.03590257]
 [0.77134099 0.61004063 0.69581609 0.29556656 0.7776923  0.5303072
  0.20529194 0.07781882 0.09571475 0.07156619]
 [0.5924794  0.68034454 0.04188841 0.60635245 0.57130127 0.03670581
  0.19104505 0.30932561 0.97156324 0.65328699]
 [0.72614049 0.51882186 0.58766837 0.38985103 0.05979935 0.0055958

#### 14. Create a random vector of size 30 and find the mean value

In [27]:
n = np.random.random(30)
print("Mean value of array elements: ", n.mean())

Mean value of array elements:  0.5195592887598917


#### 15. Create a 2d array with 1 on the border and 0 inside

In [34]:
n = np.ones((3,4))
n[1:-1,1:-1] = 0
print(n)

[[1. 1. 1. 1.]
 [1. 0. 0. 1.]
 [1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array?

In [43]:
n = np.random.random((4,4))
n[::3,:] = 0
n[:,::3] = 0
print(n)

[[0.         0.         0.         0.        ]
 [0.         0.40794548 0.6292748  0.        ]
 [0.         0.62038496 0.15691496 0.        ]
 [0.         0.         0.         0.        ]]


#### 17. What is the result of the following expression?

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [48]:
print(0*np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3*0.1)

nan
False
False
nan
True
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [45]:
n = np.diag(np.arange(1,5) , k=-1)
print(n)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern

In [50]:
n = np.zeros((8,8), dtype = int)
n[::2,1::2]=1
n[1::2,::2]=1
print(n)


[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [51]:
print(np.unravel_index(100,(6,7,8)))

(1, 5, 4)
