In [1]:
import numpy as np

In [2]:
arr = np.array([[1,2,3],
               [4,2,5]])

In [3]:
type(arr)

numpy.ndarray

In [4]:
 arr.ndim

2

In [5]:
print("shape of array: ", arr.shape)

shape of array:  (2, 3)


In [6]:
print("size of array: ", arr.size)

size of array:  6


In [7]:
print("Array stores elements of type: ",  arr.dtype)

Array stores elements of type:  int32


In [8]:
a = np.array([[1,2,4],[5,6,8]], dtype= 'float')

In [9]:
print("array created using passed list:\n ", a)

array created using passed list:
  [[1. 2. 4.]
 [5. 6. 8.]]


In [10]:
b = np.array((1,2,3))

In [12]:
print("\narray created using passed tuple:\n", b)


array created using passed tuple:
 [1 2 3]


In [13]:
c = np.zeros((3,4))

In [14]:
print("array intialised with allzeroes:\n", c)

array intialised with allzeroes:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [15]:
d = np.full((3,3), 6 , dtype = 'complex')

In [16]:
print(d)

[[6.+0.j 6.+0.j 6.+0.j]
 [6.+0.j 6.+0.j 6.+0.j]
 [6.+0.j 6.+0.j 6.+0.j]]


In [17]:
e = np.random.random((2,2,))

In [18]:
print("random array:\n", e)

random array:
 [[0.59109232 0.15582304]
 [0.56398339 0.25983714]]


In [21]:
f = np.arange(0,30,5)

In [22]:
print("sequential array with step 5:\n", f)

sequential array with step 5:
 [ 0  5 10 15 20 25]


In [23]:
np.ones((3,4)) 

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [24]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [25]:
np.arange?

In [26]:
f = np.linspace(0,5,10)

In [27]:
print("sequential array with 10 values between 0 and 5:\n", f)

sequential array with 10 values between 0 and 5:
 [0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]


In [28]:
arr = np.array([[1, 2, 4, 5 ],
                [5, 6, 7, 8],
                [8, 9 ,3, 0]])

In [29]:
newarr = arr.reshape(2, 2, 3)

In [30]:
newarr

array([[[1, 2, 4],
        [5, 5, 6]],

       [[7, 8, 8],
        [9, 3, 0]]])

In [31]:
 flarr = arr.flatten()

In [32]:
print("flattened array:\n",flarr)

flattened array:
 [1 2 4 5 5 6 7 8 8 9 3 0]


In [33]:
arr = np.array([[1, 2, 0, 4],
               [2, 3, 0 ,9],
               [4, 5, 6, 7]])

In [34]:
temp = arr[:2 , : : 2]

In [35]:
print("array with first 2 rows and alternate colmns:\n", temp)

array with first 2 rows and alternate colmns:
 [[1 0]
 [2 0]]


In [44]:
cond = arr>0

In [45]:
cond

array([[ True,  True, False,  True],
       [ True,  True, False,  True],
       [ True,  True,  True,  True]])

In [46]:
z = arr[cond]

In [47]:
z

array([1, 2, 4, 2, 3, 9, 4, 5, 6, 7])

In [48]:
a = np.array([1,2,3,4])

In [49]:
print("adding 1 to every element:", a+1)
print("substacting 3 from every element:", a-3)
print("multiplying eac element  by 10: ", a*10)
print("squarring every element: ", a**2)

adding 1 to every element: [2 3 4 5]
substacting 3 from every element: [-2 -1  0  1]
multiplying eac element  by 10:  [10 20 30 40]
squarring every element:  [ 1  4  9 16]


In [53]:
a = np.array([[1,2,3], [3,4,5], [9,6,10]])

In [57]:
print("Transpose of array:\n",a.T)

Transpose of array:
 [[ 1  3  9]
 [ 2  4  6]
 [ 3  5 10]]


In [58]:
a = a.T

In [59]:
a

array([[ 1,  3,  9],
       [ 2,  4,  6],
       [ 3,  5, 10]])

In [64]:
print("largest element is : ", a.max())
print("Row wise maximum element:", a.max(axis=1))
print("Column wise minimum element: ", a.min(axis=0))
print("sum of all array elements:", a.sum)
print("cumulative sum along each row:\n", a.cumsum(axis=1))

largest element is :  10
Row wise maximum element: [ 9  6 10]
Column wise minimum element:  [1 3 6]
sum of all array elements: <built-in method sum of numpy.ndarray object at 0x0000029725E47B70>
cumulative sum along each row:
 [[ 1  4 13]
 [ 2  6 12]
 [ 3  8 18]]


In [66]:
a = np.array([[1,2],
              [3,4]])
b = np.array([[5,6],
             [7,8]])

In [67]:
print("array sum:\n", a + b)
print("array multiplication:\n", a*b)
print("Matrix multiplication:\n",a.dot(b))

array sum:
 [[ 6  8]
 [10 12]]
array multiplication:
 [[ 5 12]
 [21 32]]
Matrix multiplication:
 [[19 22]
 [43 50]]


In [68]:
print("Vertical stacking:\n",np.vstack((a,b)))
print("horizontal stacking:\n", np.hstack((a,b)))
c = [5,6]
print("column stacking:\n", np.column_stack((a,c)))
print("concatenating to 2nd axis:\n", np.concatenate((a,b),1))

Vertical stacking:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]
horizontal stacking:
 [[1 2 5 6]
 [3 4 7 8]]
column stacking:
 [[1 2 5]
 [3 4 6]]
concatenating to 2nd axis:
 [[1 2 5 6]
 [3 4 7 8]]
